openapi: 3.0.3
info:
  title: ELEVATORSYSTEM
  version: 0.0.0
paths:
  /buildings/:
    get:
      operationId: buildings_list
      description: Creating ,Updating ,Viewing and deleting the buildings
      tags:
      - buildings
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Building'
          description: ''
    post:
      operationId: buildings_create
      description: Creating ,Updating ,Viewing and deleting the buildings
      tags:
      - buildings
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Building'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Building'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Building'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Building'
          description: ''
  /buildings/{id}/:
    get:
      operationId: buildings_retrieve
      description: Creating ,Updating ,Viewing and deleting the buildings
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - buildings
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Building'
          description: ''
    put:
      operationId: buildings_update
      description: Creating ,Updating ,Viewing and deleting the buildings
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - buildings
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Building'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Building'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Building'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Building'
          description: ''
    patch:
      operationId: buildings_partial_update
      description: Creating ,Updating ,Viewing and deleting the buildings
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - buildings
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedBuilding'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedBuilding'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedBuilding'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Building'
          description: ''
    delete:
      operationId: buildings_destroy
      description: Creating ,Updating ,Viewing and deleting the buildings
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - buildings
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /elevator/:
    get:
      operationId: elevator_list
      description: Creating ,Updating ,Viewing the Elevators
      tags:
      - elevator
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Elevator'
          description: ''
    post:
      operationId: elevator_create
      description: Creating ,Updating ,Viewing the Elevators
      tags:
      - elevator
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Elevator'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Elevator'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Elevator'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Elevator'
          description: ''
  /elevator/{id}/:
    get:
      operationId: elevator_retrieve
      description: Creating ,Updating ,Viewing the Elevators
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - elevator
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Elevator'
          description: ''
    put:
      operationId: elevator_update
      description: Creating ,Updating ,Viewing the Elevators
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - elevator
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Elevator'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Elevator'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Elevator'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Elevator'
          description: ''
    patch:
      operationId: elevator_partial_update
      description: Creating ,Updating ,Viewing the Elevators
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - elevator
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedElevator'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedElevator'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedElevator'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Elevator'
          description: ''
    delete:
      operationId: elevator_destroy
      description: Creating ,Updating ,Viewing the Elevators
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - elevator
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /elevator_status/:
    post:
      operationId: elevator_status_create
      description: for getting the status of elevator
      tags:
      - elevator_status
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ElevatorStatus'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ElevatorStatus'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ElevatorStatus'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ElevatorStatus'
          description: ''
  /request_inside_elevator/:
    post:
      operationId: request_inside_elevator_create
      description: handling requests inside the elevator
      tags:
      - request_inside_elevator
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ElevatorRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ElevatorRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ElevatorRequest'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ElevatorRequest'
          description: ''
  /request_outside_elevator/:
    post:
      operationId: request_outside_elevator_create
      tags:
      - request_outside_elevator
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ElevatorRequestOutside'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ElevatorRequestOutside'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ElevatorRequestOutside'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ElevatorRequestOutside'
          description: ''
components:
  schemas:
    Building:
      type: object
      description: Serializer for building
      properties:
        id:
          type: integer
          readOnly: true
        b_name:
          type: string
          maxLength: 50
        total_elevators:
          type: integer
        minimumfloors:
          type: integer
        totalfloors:
          type: integer
      required:
      - b_name
      - id
      - total_elevators
      - totalfloors
    Elevator:
      type: object
      description: Serializer for elevator status
      properties:
        id:
          type: integer
          readOnly: true
        e_number:
          type: integer
        running_status:
          $ref: '#/components/schemas/RunningStatusEnum'
        current_floor:
          type: integer
        is_running:
          type: boolean
        is_door_open:
          type: boolean
        building:
          type: integer
      required:
      - building
      - e_number
      - id
    ElevatorRequest:
      type: object
      description: Handling request inside elevator
      properties:
        elevator_id:
          type: integer
        building_id:
          type: integer
        destination_floor:
          type: integer
      required:
      - building_id
      - destination_floor
      - elevator_id
    ElevatorRequestOutside:
      type: object
      description: |-
        A person standing outside the building requesting for an elevator can only send information about building and
        the destination floor
      properties:
        building_id:
          type: integer
        destination_floor:
          type: integer
      required:
      - building_id
      - destination_floor
    ElevatorStatus:
      type: object
      description: Updating the status for elevator
      properties:
        elevator_id:
          type: integer
      required:
      - elevator_id
    PatchedBuilding:
      type: object
      description: Serializer for building
      properties:
        id:
          type: integer
          readOnly: true
        b_name:
          type: string
          maxLength: 50
        total_elevators:
          type: integer
        minimumfloors:
          type: integer
        totalfloors:
          type: integer
    PatchedElevator:
      type: object
      description: Serializer for elevator status
      properties:
        id:
          type: integer
          readOnly: true
        e_number:
          type: integer
        running_status:
          $ref: '#/components/schemas/RunningStatusEnum'
        current_floor:
          type: integer
        is_running:
          type: boolean
        is_door_open:
          type: boolean
        building:
          type: integer
    RunningStatusEnum:
      enum:
      - going_up
      - standing_still
      - going_down
      - not_working
      type: string
      description: |-
        * `going_up` - Going_Up
        * `standing_still` - Standing_Still
        * `going_down` - Going_Down
        * `not_working` - Not_Working
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
